name: Archive


on:
  push:
    tags: [ 0.* ]
  workflow_dispatch:
    inputs:
      logLevel:

jobs:
  release-osx:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks


      - name: Prepare create-dmg
        run: npm install --global create-dmg

      - name: Prepare WebFiles Dependencies
        run: |
          cd IINA+/WebFiles/
          npm install

      - name: SPM
        run: xcodebuild -resolvePackageDependencies

      - name: Archive
        run: xcodebuild archive -project IINA+.xcodeproj -scheme IINA+ -archivePath archive/IINA+.xcarchive -showBuildTimingSummary -allowProvisioningUpdates

      - name: CodeSign And Package
        shell: zsh {0}
        run: |
          cd archive/IINA+.xcarchive/Products/Applications/
          codesign --deep --force --timestamp --sign ${{ secrets.SIGN_NAME }} *.app
          create-dmg *.app
          codesign --deep --force --timestamp --sign ${{ secrets.SIGN_NAME }} *.dmg

          ditto -c -k --sequesterRsrc --keepParent *.app "$(basename *.dmg .dmg)".zip
          ditto -c -k --sequesterRsrc --keepParent ../../dSYMs dSYMs.zip
